name: Build, test, deploy documentation
env:
  BUILD_DIR: ${{github.workspace}}
  JOB_NUMBER: ${{github.run_number}}

on:
  push:
    branches: [ develop, feature/github_actions ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

concurrency: ${{github.ref}}

defaults:
  run:
    shell: bash

jobs:

  build-and-test:
    name: Build and test on ${{matrix.db_version_name}} DB
    env:
      ORACLE_VERSION: ${{matrix.oracle-version}}
      CONNECTION_STR: ${{matrix.connection-str}}
      ORACLE_PASSWORD: oracle
      DOCKER_VOLUME: ${{matrix.docker-volume}}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - oracle-version: "gvenzl/oracle-xe:11-full"
            connection-str: '127.0.0.1:1521/XE'
            id: 1
            db_version_name: '11xe'
# TODO - need to add healthcheck.sh into our containers
#          - oracle-version: "utplsqlv3/oracledb:12c-r1-se2-small"
#            connection-str: '127.0.0.1:1521/ORCLCDB'
#            id: 2
#            db_version_name: '12.1se'
#          - oracle-version: "utplsqlv3/oracledb:12c-r2-se2-small"
#            connection-str: '127.0.0.1:1521/ORCLCDB'
#            id: 3
#            db_version_name: '12.2se'
          - oracle-version: "gvenzl/oracle-xe:18-slim"
            connection-str: '127.0.0.1:1521/XE'
            id: 4
            db_version_name: '18xe'
#          - oracle-version: "utplsqlv3/oracledb:18c-se2-small"
#            connection-str: '127.0.0.1:1521/ORCLCDB'
#            id: 5
#            db_version_name: '18se'
#          - oracle-version: "utplsqlv3/oracledb:19c-se2-small"
#            connection-str: '127.0.0.1:1521/ORCLCDB'
#            id: 6
#            db_version_name: '19se'
          - oracle-version: "gvenzl/oracle-xe:21-slim"
            connection-str: '127.0.0.1:1521/XE'
            id: 7
            db_version_name: '21xe'

    services:
      oracle:
        image: ${{matrix.oracle-version}}
        env:
          ORACLE_PASSWORD: oracle
#        credentials:
#          username: ${{ secrets.DOCKER_USER }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nelonoel/branch-name@v1.0.1
      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .github/variables/.env


      - name: Set build version number env variables
        id: set-build-version-number-vars
        run: .github/scripts/set_version_numbers_env.sh

      - name: Update project version & build number to verify that code is deployable after the update
        id: update-project-version
        run:  .travis/update_project_version.sh

      - name: Download latest utPLSQL release
        run: git clone --depth=1 --branch=main https://github.com/utPLSQL/utPLSQL.git $UTPLSQL_DIR

      - name: Update privileges on sources
        run: chmod -R go+w ./{source,test,examples,${UTPLSQL_DIR}/source}

      - name: Add OJDBC home
        id: get-ojdbc
        run:  mkdir -p ${OJDBC_HOME} && curl -Lk -o ${OJDBC_HOME}/ojdbc8.jar ${OJDBC_URL}/ojdbc8.jar && curl -Lk -o ${OJDBC_HOME}/orai18n.jar ${OJDBC_URL}/orai18n.jar

      - name: Install utPLSQL-cli
        id: install-utplsql-cli
        run: curl -Lk -o utPLSQL-cli.zip "https://github.com/utPLSQL/utPLSQL-cli/releases/download/v3.1.8/utPLSQL-cli.zip" && unzip utPLSQL-cli.zip && chmod -R u+x utPLSQL-cli

      - name: Install utPLSQL
        id: install-utplsql
        run: docker run --rm -v $(pwd):/utPLSQL -w /utPLSQL --network host --entrypoint bash ${DOCKER_ENV} ${ORACLE_VERSION} .travis/install.sh

      - name: Install utPLSQL release
        id: install-utplsql-release
        run: docker run --rm -v $(pwd):/utPLSQL -w /utPLSQL --network host --entrypoint bash ${DOCKER_ENV} ${ORACLE_VERSION} ./.travis/install_utplsql_release.sh

      - name: Run Examples
        id: run-examples
        run: docker run --rm -v $(pwd):/utPLSQL -w /utPLSQL --network host --entrypoint bash ${DOCKER_ENV} ${ORACLE_VERSION} ./.travis/run_examples.sh

      - name: Install tests
        id: install-tests
        run: docker run --rm -v $(pwd):/utPLSQL -w /utPLSQL --network host --entrypoint bash ${DOCKER_ENV} ${ORACLE_VERSION} ./test/install_tests.sh

      - name: Run Tests
        id: run-tests
        run: bash test/run_tests.sh

      - name: Validate utPLSQL reports format
        id: validate-reports-format
        run:  bash .travis/validate_report_files.sh

      - name: SonarCloud Scan
        id: sonar
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish:
    name: Deploy documentation
    needs: [build-and-test]
    concurrency: publish
    runs-on: ubuntu-latest
    if: |
      ${{ github.repository == 'utPLSQL/utPLSQL' && github.base_ref == null
        && ( startsWith( github.ref, 'refs/heads/release/v' )  || github.ref == 'refs/heads/develop' ) 
      }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #Populates the value of BRANCH_NAME env variable
      - uses: nelonoel/branch-name@v1.0.1
      - uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .github/variables/.env

      - name: Set buid version number env variables
        id: set-build-version-number-vars
        run: .github/scripts/set_version_numbers_env.sh

      - name: Update project version & build number in source code and documentation
        id: update-project-version
        run:  .travis/update_project_version.sh
        
      - name: Push version update to repository
        id: push-version-number-update
        run:  .travis/push_project_version.sh

      - name: Copy and push documentation to utPLSQL-github-io repo
        id: push-documentation
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: .travis/push_docs_to_github_io.sh

  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs: [build-and-test, publish]
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          name: 'Github Actions[bot]'
          icon_url: 'https://octodex.github.com/images/mona-the-rivetertocat.png'
